/**
 * A bot instance is one TeamSpeak identity on one server, backed by its own headless
 * client container: its own PulseAudio sink, its own ClientQuery socket, its own queue.
 *
 * Everything is addressed by host:port — never localhost. That single rule is what lets a
 * client container run on a remote x86 host while the backend stays native, and it is also
 * what makes running many bots a matter of configuration rather than refactoring.
 */

export const CONNECTION_STATES = [
  'disconnected',
  'connecting',
  'connected',
  'error',
] as const;
export type ConnectionState = (typeof CONNECTION_STATES)[number];

export interface ClientQueryEndpoint {
  readonly host: string;
  readonly port: number;
  /** Generated by the ClientQuery plugin during the one-time VNC bootstrap. Secret. */
  readonly apiKey: string;
}

export interface AudioEndpoint {
  /** PulseAudio server address, e.g. `tcp:ts3-client-party:4713`. */
  readonly pulseServer: string;
  /** Null-sink ffmpeg writes into, e.g. `bot_sink`. */
  readonly sinkName: string;
}

export interface TeamSpeakTarget {
  readonly host: string;
  readonly port: number;
  readonly nickname: string;
  /** Channel the bot returns to on `!leave` and joins on connect. */
  readonly homeChannelId: number | null;
}

export interface InstanceSummary {
  readonly id: string;
  readonly name: string;
  readonly enabled: boolean;
  readonly teamspeak: TeamSpeakTarget;
  readonly connection: ConnectionState;
  readonly connectionError: string | null;
  readonly currentChannel: ChannelRef | null;
}

export interface ChannelRef {
  readonly id: number;
  readonly name: string;
}

export interface ChannelClient {
  readonly clid: number;
  readonly uid: string;
  readonly nickname: string;
  readonly serverGroupIds: readonly number[];
}
