/**
 * A bot instance is one TeamSpeak identity on one server, backed by its own headless
 * client container: its own PulseAudio sink, its own ClientQuery socket, its own queue.
 *
 * Everything is addressed by host:port — never localhost. That single rule is what lets a
 * client container run on a remote x86 host while the backend stays native, and it is also
 * what makes running many bots a matter of configuration rather than refactoring.
 */

export const CONNECTION_STATES = [
  'disconnected',
  'connecting',
  'connected',
  'error',
] as const;
export type ConnectionState = (typeof CONNECTION_STATES)[number];

export interface ClientQueryEndpoint {
  readonly host: string;
  readonly port: number;
  /** Generated by the ClientQuery plugin during the one-time VNC bootstrap. Secret. */
  readonly apiKey: string;
}

export interface AudioEndpoint {
  /** PulseAudio server address, e.g. `tcp:ts3-client-party:4713`. */
  readonly pulseServer: string;
  /** Null-sink ffmpeg writes into, e.g. `bot_sink`. */
  readonly sinkName: string;
}

export interface TeamSpeakTarget {
  readonly host: string;
  readonly port: number;
  readonly nickname: string;
  /**
   * Channel to join on connect, by name.
   *
   * A name rather than an id: ids change when a channel is recreated, and an operator types
   * what they can see. Re-applied after every reconnect, because a server restart drops the
   * bot back into the default channel.
   */
  readonly channel: string | null;
  readonly channelPassword: string | null;
  /** Channel the bot returns to on `!leave`. */
  readonly homeChannelId: number | null;
}

/**
 * The publishable half of a TeamSpeak target.
 *
 * Separate from {@link TeamSpeakTarget} on purpose: that one carries the channel password,
 * and a summary sent to every panel must not be able to include it. Making it a distinct
 * type means leaking a secret is a compile error rather than an oversight.
 */
export interface PublicTeamSpeakTarget {
  readonly host: string;
  readonly port: number;
  readonly nickname: string;
  readonly channel: string | null;
  readonly homeChannelId: number | null;
}

export interface InstanceSummary {
  readonly id: string;
  readonly name: string;
  readonly enabled: boolean;
  readonly teamspeak: PublicTeamSpeakTarget;
  readonly connection: ConnectionState;
  readonly connectionError: string | null;
  readonly currentChannel: ChannelRef | null;
}

export interface ChannelRef {
  readonly id: number;
  readonly name: string;
}

export interface ChannelClient {
  readonly clid: number;
  readonly uid: string;
  readonly nickname: string;
  readonly serverGroupIds: readonly number[];
}
